--LIKE OPERATAR--
SELECT * FROM employee WHERE e_name LIKE't%';

SELECT * FROM employee WHERE e_age LIKE '4_';
--BETWEEN OPERATAR--
SELECT * FROM employee WHERE e_age BETWEEN 30 AND 50;
SELECT * FROM employee WHERE e_salary BETWEEN 30000 AND 60000;

